[[main]]
name = "About"
pageRef = "about"
weight = 10

[[main]]
name = "Research"
pageRef = "research"
weight = 20

[[main]]
name = "Teaching"
pageRef = "teaching"
weight = 30

[[main]]
name = "Writing"
pageRef = "writing"
weight = 40

[[main]]
name = "Resume"
url = "/resume.pdf"
weight = 50

[[main]]
  name = "Email"
  pre = "envelope"
  url = "mailto:shriya.rangarajan@gmail.com?subject=Hello!"
  weight = 60

[[main]]
  name = ""
  pre = "linkedin"
  url = "https://www.linkedin.com/in/shriyarangarajan/"
  weight = 70